import type { Property, BlogPost, Testimonial, Agent, BlogCategory } from "@/types";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-1",
    name: "Tunde Adeyemi",
    title: "Senior Real Estate Consultant",
    email: "tunde@futurehome.com",
    phone: "+234 801 234 5678",
    whatsapp: "+234 801 234 5678",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    bio: "With over 10 years of experience in Lagos real estate market, Tunde specializes in luxury residential properties.",
    licenseNumber: "Lagos/REC/2015/0042",
    yearsExperience: 10,
    specialties: ["Luxury Homes", "Commercial Properties", "Investment Properties"],
    languages: ["English", "Yoruba"],
    social: { linkedin: "https://linkedin.com/in/tunde", instagram: "https://instagram.com/tunde" },
    rating: 4.9,
    reviewCount: 127,
    propertiesCount: 89,
  },
  {
    id: "agent-2",
    name: "Chioma Eze",
    title: "Property Investment Advisor",
    email: "chioma@futurehome.com",
    phone: "+234 802 345 6789",
    whatsapp: "+234 802 345 6789",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=400&fit=crop&crop=face",
    bio: "Chioma helps investors identify high-yield properties across Lagos with data-driven insights.",
    licenseNumber: "Lagos/REC/2016/0078",
    yearsExperience: 8,
    specialties: ["Investment Properties", "Off-plan", "Rental Yield"],
    languages: ["English", "Igbo"],
    social: { linkedin: "https://linkedin.com/in/chioma", twitter: "https://twitter.com/chioma" },
    rating: 4.8,
    reviewCount: 95,
    propertiesCount: 67,
  },
  {
    id: "agent-3",
    name: "Abdul Balogun",
    title: "Commercial Real Estate Specialist",
    email: "abdul@futurehome.com",
    phone: "+234 803 456 7890",
    whatsapp: "+234 803 456 7890",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    bio: "Abdul has facilitated over ₦5 billion in commercial real estate transactions across Nigeria.",
    licenseNumber: "Lagos/REC/2014/0021",
    yearsExperience: 12,
    specialties: ["Commercial", "Industrial", "Land"],
    languages: ["English", "Hausa", "Arabic"],
    social: { linkedin: "https://linkedin.com/in/abdul" },
    rating: 4.7,
    reviewCount: 78,
    propertiesCount: 54,
  },
];

const createProperty = (overrides: Partial<Property>): Property => ({
  id: Math.random().toString(36).substr(2, 9),
  title: "Beautiful Property",
  description: "This is a stunning property located in one of the most prestigious neighborhoods in Lagos. Featuring modern amenities, spacious rooms, and breathtaking views.",
  shortDescription: "Stunning modern property in prime location",
  type: "apartment",
  status: "for-sale",
  category: "residential",
  listingType: "sale",
  price: 150000000,
  pricePerSqFt: 500000,
  currency: "NGN",
  location: {
    address: "1 Admiralty Way",
    city: "Lekki",
    state: "Lagos",
    country: "Nigeria",
    coordinates: { lat: 6.4474, lng: 3.4706 },
    neighborhood: "Lekki Phase 1",
    landmark: "Near Landmark Beach",
  },
  features: {
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 2,
    area: 300,
    areaUnit: "sqm",
    yearBuilt: 2022,
    floors: 1,
    floorNumber: 8,
  },
  amenities: {
    airConditioning: true,
    heating: false,
    furnished: false,
    kitchenAppliances: true,
    washerDryer: true,
    walkInCloset: true,
    fireplace: false,
    balcony: true,
    elevator: true,
    security: true,
    concierge: true,
    gym: true,
    pool: true,
    spa: false,
    tennisCourt: false,
    basketballCourt: false,
    playground: false,
    garden: true,
    rooftop: true,
    internet: true,
    cableTv: true,
    intercom: true,
    cctv: true,
    backupGenerator: true,
    solarPower: true,
    waterTreatment: true,
    wheelchairAccessible: true,
    petFriendly: true,
  },
  images: [
    { id: "1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", alt: "Property exterior", isPrimary: true, order: 0 },
    { id: "2", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop", alt: "Living room", isPrimary: false, order: 1 },
    { id: "3", url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop", alt: "Kitchen", isPrimary: false, order: 2 },
    { id: "4", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", alt: "Bedroom", isPrimary: false, order: 3 },
    { id: "5", url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&h=600&fit=crop", alt: "Bathroom", isPrimary: false, order: 4 },
  ],
  agent: MOCK_AGENTS[0],
  isFeatured: true,
  isVerified: true,
  views: 1250,
  favoritesCount: 89,
  createdAt: "2024-01-15T10:00:00Z",
  updatedAt: "2024-03-10T14:30:00Z",
  publishedAt: "2024-01-20T08:00:00Z",
  nearbyPlaces: [
    { id: "1", name: "Lekki Conservation Centre", type: "park", distance: 2500 },
    { id: "2", name: "Novare Mall", type: "shopping", distance: 1200 },
    { id: "3", name: "American International School", type: "school", distance: 1800 },
  ],
  ...overrides,
});

export const MOCK_PROPERTIES: Property[] = [
  createProperty({
    id: "prop-1",
    title: "Luxury Penthouse at Eko Atlantic",
    description: "An exquisite penthouse offering panoramic views of the Atlantic Ocean. This masterpiece features floor-to-ceiling windows, Italian marble finishes, and smart home automation throughout.",
    shortDescription: "Stunning ocean-view penthouse in Eko Atlantic",
    type: "penthouse",
    price: 850000000,
    location: { address: "Block 2, Plot 1", city: "Lagos", state: "Lagos", country: "Nigeria", neighborhood: "Eko Atlantic", coordinates: { lat: 6.4281, lng: 3.4286 } },
    features: { bedrooms: 5, bathrooms: 5, parkingSpaces: 3, area: 650, areaUnit: "sqm", yearBuilt: 2023, floorNumber: 30 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop", alt: "Penthouse exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop", alt: "Living room", isPrimary: false, order: 1 },
      { id: "3", url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop", alt: "Master bedroom", isPrimary: false, order: 2 },
      { id: "4", url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop", alt: "Kitchen", isPrimary: false, order: 3 },
    ],
    isFeatured: true,
    category: "luxury",
    agent: MOCK_AGENTS[1],
    views: 3200,
    favoritesCount: 245,
  }),
  createProperty({
    id: "prop-2",
    title: "Modern 4-Bedroom Duplex in Lekki",
    description: "A beautifully designed 4-bedroom fully detached duplex in a serene estate. Features include fitted kitchen, POP finishing, water heater, CCTV, and impressive architectural design.",
    shortDescription: "Spacious family home in prime Lekki location",
    type: "duplex",
    price: 120000000,
    location: { address: "ID Atlantic Estate, Lekki", city: "Lekki", state: "Lagos", country: "Nigeria", neighborhood: "Lekki Phase 1", coordinates: { lat: 6.4478, lng: 3.4720 } },
    features: { bedrooms: 4, bathrooms: 4, parkingSpaces: 2, area: 350, areaUnit: "sqm", yearBuilt: 2023, floors: 2 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop", alt: "Duplex exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&h=600&fit=crop", alt: "Living area", isPrimary: false, order: 1 },
      { id: "3", url: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop", alt: "Kitchen", isPrimary: false, order: 2 },
    ],
    isFeatured: true,
    agent: MOCK_AGENTS[0],
    views: 2100,
    favoritesCount: 156,
  }),
  createProperty({
    id: "prop-3",
    title: "Premium Apartment at Victoria Island",
    description: "An elegantly finished 3-bedroom apartment in a high-rise with city views. World-class amenities including gym, pool, and 24/7 security.",
    shortDescription: "Elegant apartment in upscale Victoria Island",
    type: "apartment",
    price: 200000000,
    location: { address: "15A Ozumba Mbadiwe Avenue", city: "Victoria Island", state: "Lagos", country: "Nigeria", neighborhood: "Victoria Island", coordinates: { lat: 6.4284, lng: 3.4266 } },
    features: { bedrooms: 3, bathrooms: 3, parkingSpaces: 2, area: 280, areaUnit: "sqm", yearBuilt: 2021, floorNumber: 12 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop", alt: "Apartment exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=600&fit=crop", alt: "Interior view", isPrimary: false, order: 1 },
      { id: "3", url: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&h=600&fit=crop", alt: "Balcony view", isPrimary: false, order: 2 },
    ],
    isFeatured: true,
    listingType: "rent",
    agent: MOCK_AGENTS[2],
    views: 1800,
    favoritesCount: 98,
  }),
  createProperty({
    id: "prop-4",
    title: "Beachfront Villa in Banana Island",
    description: "A prestigious beachfront villa offering unparalleled luxury. This architectural masterpiece sits on 2,000 sqm with private beach access and resort-style amenities.",
    shortDescription: "Exclusive beachfront living in Banana Island",
    type: "villa",
    price: 2500000000,
    location: { address: "Ocean Drive, Banana Island", city: "Ikoyi", state: "Lagos", country: "Nigeria", neighborhood: "Banana Island", coordinates: { lat: 6.4396, lng: 3.4290 } },
    features: { bedrooms: 7, bathrooms: 6, parkingSpaces: 5, area: 1200, areaUnit: "sqm", yearBuilt: 2020, floors: 2 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", alt: "Villa exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", alt: "Pool area", isPrimary: false, order: 1 },
      { id: "3", url: "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&h=600&fit=crop", alt: "Interior", isPrimary: false, order: 2 },
    ],
    isFeatured: true,
    category: "luxury",
    agent: MOCK_AGENTS[1],
    views: 4500,
    favoritesCount: 312,
  }),
  createProperty({
    id: "prop-5",
    title: "Contemporary Office Space in GRA Ikeja",
    description: "Grade A office space of 500 sqm in a central business district with excellent accessibility, ample parking, and fiber optic connectivity.",
    shortDescription: "Prime commercial space in GRA Ikeja business district",
    type: "office",
    price: 350000000,
    listingType: "sale",
    category: "commercial",
    location: { address: "Oba Akran Avenue", city: "Ikeja", state: "Lagos", country: "Nigeria", neighborhood: "GRA Ikeja", coordinates: { lat: 6.5964, lng: 3.3420 } },
    features: { bedrooms: 0, bathrooms: 4, parkingSpaces: 10, area: 500, areaUnit: "sqm", yearBuilt: 2022, floorNumber: 15 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop", alt: "Office building", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop", alt: "Office interior", isPrimary: false, order: 1 },
    ],
    isFeatured: false,
    agent: MOCK_AGENTS[2],
    views: 890,
    favoritesCount: 45,
  }),
  createProperty({
    id: "prop-6",
    title: "Serviced Apartment in Oniru",
    description: "Fully serviced 2-bedroom apartment with hotel-like amenities. High-speed internet, daily cleaning, concierge, and 24-hour power supply included.",
    shortDescription: "Hotel-style serviced apartment in Oniru",
    type: "apartment",
    price: 65000000,
    listingType: "rent",
    location: { address: "King George V Drive, Oniru", city: "Victoria Island", state: "Lagos", country: "Nigeria", neighborhood: "Oniru", coordinates: { lat: 6.4350, lng: 3.4310 } },
    features: { bedrooms: 2, bathrooms: 2, parkingSpaces: 1, area: 120, areaUnit: "sqm", yearBuilt: 2023, floorNumber: 5 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", alt: "Apartment exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop", alt: "Living area", isPrimary: false, order: 1 },
    ],
    isFeatured: false,
    agent: MOCK_AGENTS[0],
    views: 1340,
    favoritesCount: 78,
  }),
  createProperty({
    id: "prop-7",
    title: "Massive Land in Ibeju-Lekki",
    description: "An exceptional investment opportunity - 2,000 square meters of dry, well-located land in the rapidly developing Ibeju-Lekki corridor. Perfect for residential or commercial development.",
    shortDescription: "Premium dry land in Ibeju-Lekki corridor",
    type: "land",
    price: 45000000,
    listingType: "sale",
    category: "land",
    location: { address: "Lakowe Lakes Road, Ibeju-Lekki", city: "Ibeju-Lekki", state: "Lagos", country: "Nigeria", coordinates: { lat: 6.4956, lng: 3.5988 } },
    features: { bedrooms: 0, bathrooms: 0, parkingSpaces: 0, area: 2000, areaUnit: "sqm", yearBuilt: 0 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop", alt: "Land view", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&h=600&fit=crop", alt: "Surrounding area", isPrimary: false, order: 1 },
    ],
    isFeatured: false,
    agent: MOCK_AGENTS[2],
    views: 670,
    favoritesCount: 34,
  }),
  createProperty({
    id: "prop-8",
    title: "Waterfront Home in Chevron",
    description: "Stunning 5-bedroom terrace home along the Chevron waterfront. Features private dock, home automation, staff quarters, and manicured gardens.",
    shortDescription: "Waterfront luxury home with private dock",
    type: "townhouse",
    price: 380000000,
    location: { address: "Chevron Drive", city: "Lekki", state: "Lagos", country: "Nigeria", neighborhood: "Chevron", coordinates: { lat: 6.4410, lng: 3.4660 } },
    features: { bedrooms: 5, bathrooms: 5, parkingSpaces: 3, area: 450, areaUnit: "sqm", yearBuilt: 2022, floors: 3 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", alt: "Home exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop", alt: "Living room", isPrimary: false, order: 1 },
      { id: "3", url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop", alt: "Waterfront view", isPrimary: false, order: 2 },
    ],
    isFeatured: true,
    agent: MOCK_AGENTS[1],
    views: 2800,
    favoritesCount: 198,
  }),
  createProperty({
    id: "prop-9",
    title: "Student Accommodation in Yaba",
    description: "Well-designed 1-bedroom apartment in bustling Yaba area, perfect for young professionals or students. Close to tech hubs and educational institutions.",
    shortDescription: "Affordable modern apartment in Yaba",
    type: "apartment",
    price: 25000000,
    listingType: "rent",
    location: { address: "Akibo Close, Yaba", city: "Yaba", state: "Lagos", country: "Nigeria", neighborhood: "Yaba", coordinates: { lat: 6.5095, lng: 3.3792 } },
    features: { bedrooms: 1, bathrooms: 1, parkingSpaces: 1, area: 55, areaUnit: "sqm", yearBuilt: 2021, floorNumber: 3 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop", alt: "Apartment exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop", alt: "Interior", isPrimary: false, order: 1 },
    ],
    isFeatured: false,
    agent: MOCK_AGENTS[0],
    views: 920,
    favoritesCount: 56,
  }),
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "Dr. Funke Akindele",
    role: "Medical Doctor",
    company: "Lagos University Teaching Hospital",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    content: "Future Home Properties made our dream of owning a home in Victoria Island a reality. Their professionalism, market knowledge, and dedication to finding the perfect property for our family was outstanding. We couldn't be happier with our new home!",
    rating: 5,
    propertyId: "prop-3",
    propertyTitle: "Premium Apartment at Victoria Island",
    createdAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "test-2",
    name: "Emeka Obi",
    role: "Tech Entrepreneur",
    company: "FinTech Solutions",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
    content: "As a busy professional, I needed a property agent who understood my requirements and could handle everything efficiently. Future Home exceeded all expectations. They found me a perfect investment property that has already appreciated significantly.",
    rating: 5,
    propertyId: "prop-5",
    propertyTitle: "Contemporary Office Space in GRA Ikeja",
    createdAt: "2024-01-28T10:00:00Z",
  },
  {
    id: "test-3",
    name: "Aisha Musa",
    role: "Banking Executive",
    company: "First Bank of Nigeria",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
    content: "I've worked with several real estate companies, but none compare to Future Home Properties. Their attention to detail, transparent communication, and genuine care for their clients sets them apart. They truly go above and beyond.",
    rating: 5,
    propertyId: "prop-8",
    propertyTitle: "Waterfront Home in Chevron",
    createdAt: "2024-03-05T10:00:00Z",
  },
  {
    id: "test-4",
    name: "Oluwaseun Adeyinka",
    role: "Real Estate Investor",
    company: "Adeyinka Holdings",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    content: "Future Home Properties has been instrumental in building my real estate portfolio. Their investment advice is always sound, and they have an uncanny ability to identify properties with the highest ROI potential. Truly top-notch service.",
    rating: 5,
    propertyId: "prop-7",
    propertyTitle: "Massive Land in Ibeju-Lekki",
    createdAt: "2024-02-20T10:00:00Z",
  },
];

const defaultAuthor = {
  id: "author-fh",
  name: "Future Home Properties",
  title: "Real Estate Expert",
  image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
  bio: "Future Home Properties is a leading real estate firm in Nigeria, helping clients buy, sell, and invest in premium properties.",
  social: { linkedin: "https://linkedin.com/company/futurehome" },
};

const uncategorized: BlogCategory = { id: "cat-uncategorized", name: "Uncategorized", slug: "uncategorized", description: "General real estate articles", postCount: 15 };
const land: BlogCategory = { id: "cat-land", name: "Land", slug: "land", description: "Land investment insights", postCount: 4 };
const business: BlogCategory = { id: "cat-business", name: "Business", slug: "business", description: "Real estate business insights", postCount: 3 };
const construction: BlogCategory = { id: "cat-construction", name: "Construction", slug: "construction", description: "Construction and development", postCount: 2 };
const realEstate: BlogCategory = { id: "cat-real-estate", name: "Real Estate", slug: "real-estate", description: "Real estate market insights", postCount: 6 };

const blogImage = "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop";
const blogImageAlt = "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop";
const blogImageAlt2 = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop";
const blogImageAlt3 = "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200&h=800&fit=crop";
const blogImageAlt4 = "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop";
const blogImageAlt5 = "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=1200&h=800&fit=crop";
const blogImageAlt6 = "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=800&fit=crop";
const blogImageAlt7 = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=800&fit=crop";
const blogImageAlt8 = "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1200&h=800&fit=crop";
const blogImageAlt9 = "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=1200&h=800&fit=crop";
const blogImageAlt10 = "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=1200&h=800&fit=crop";
const blogImageAlt11 = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=800&fit=crop";
const blogImageAlt12 = "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop";
const blogImageAlt13 = "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&h=800&fit=crop";
const blogImageAlt14 = "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop";

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    title: "Waterfront Smart City in Lekki",
    slug: "waterfront-smart-city-in-lekki",
    excerpt: "Explore the vision behind the new waterfront smart city transforming Lekki into a world-class urban destination for living, working, and leisure.",
    content: "The Lekki corridor is rapidly evolving into one of Africa's most ambitious urban developments. The waterfront smart city concept blends modern infrastructure, sustainable design, and technology-driven services to create a new standard of living in Lagos. From smart traffic systems to integrated residential and commercial zones, this development is positioning Lekki as a global investment hotspot. Investors and homebuyers are taking note of the long-term value being created along this coastline.",
    coverImage: blogImage,
    author: defaultAuthor,
    category: realEstate,
    tags: ["lekki", "smart city", "waterfront", "lagos"],
    isFeatured: true,
    isPublished: true,
    publishedAt: "2023-06-15T08:00:00Z",
    createdAt: "2023-06-10T10:00:00Z",
    updatedAt: "2023-06-15T08:00:00Z",
    readTime: 6,
    views: 3200,
    likes: 210,
    seo: { metaTitle: "Waterfront Smart City in Lekki", metaDescription: "Explore the new waterfront smart city transforming Lekki.", keywords: ["lekki", "smart city", "waterfront"] },
  },
  {
    id: "blog-2",
    title: "How to Buy a Home in 2026: A Step-by-Step Guide",
    slug: "how-to-buy-a-home-2026",
    excerpt: "A practical, step-by-step guide to buying a home in 2026 — from understanding the market and securing financing to closing the deal with confidence.",
    content: "Buying a home in 2026 is about preparation, not timing. Start by understanding your local market, getting pre-approved for a mortgage, and defining your true budget. Work with a trusted real estate agent, tour homes with purpose, and make a strong offer backed by solid financing. Inspections, appraisals, and digital closings have made the process faster. With the right plan and the right professional, buying a home in 2026 can feel clear, strategic, and rewarding.",
    coverImage: blogImageAlt,
    author: defaultAuthor,
    category: realEstate,
    tags: ["home buying", "2026", "guide", "mortgage"],
    isFeatured: true,
    isPublished: true,
    publishedAt: "2023-05-20T08:00:00Z",
    createdAt: "2023-05-15T10:00:00Z",
    updatedAt: "2023-05-20T08:00:00Z",
    readTime: 10,
    views: 4500,
    likes: 320,
    seo: { metaTitle: "How to Buy a Home in 2026", metaDescription: "Step-by-step guide to buying a home in 2026.", keywords: ["home buying", "2026", "guide"] },
  },
  {
    id: "blog-3",
    title: "Tiwa Savage's Journey: From Music Queen to Real Estate Investor",
    slug: "tiwa-savage-real-estate-investor",
    excerpt: "How Tiwa Savage is channeling her success in music into smart real estate investments and inspiring a new generation of investors.",
    content: "Tiwa Savage is not just a music icon — she is becoming a savvy real estate investor. Her journey from the stage to the property market highlights the power of diversification and long-term wealth building. By investing in prime properties and partnering with reputable developers, she is building a portfolio that extends far beyond entertainment. Her story is inspiring a new generation of Nigerians to take real estate investment seriously.",
    coverImage: blogImageAlt2,
    author: defaultAuthor,
    category: business,
    tags: ["tiwa savage", "investment", "celebrity", "real estate"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2023-04-18T08:00:00Z",
    createdAt: "2023-04-12T10:00:00Z",
    updatedAt: "2023-04-18T08:00:00Z",
    readTime: 5,
    views: 5100,
    likes: 410,
    seo: { metaTitle: "Tiwa Savage Real Estate Investor", metaDescription: "Tiwa Savage's journey into real estate investment.", keywords: ["tiwa savage", "real estate", "investment"] },
  },
  {
    id: "blog-4",
    title: "My 2 KOBO on Real Estate Off-Plan Investment!",
    slug: "my-2-kobo-real-estate-off-plan-investment",
    excerpt: "A candid reflection on off-plan real estate investing — the opportunities, the risks, and the lessons learned from putting real money on the line.",
    content: "Off-plan investing is one of the most talked-about strategies in Nigerian real estate. The promise of buying at today's price and selling at tomorrow's value is real, but so are the risks. From developer delays to title complications, every off-plan purchase requires thorough due diligence. This piece shares hard-won lessons on vetting developers, verifying land documents, and structuring payments to protect your capital while maximizing returns.",
    coverImage: blogImageAlt3,
    author: defaultAuthor,
    category: realEstate,
    tags: ["off-plan", "investment", "real estate", "nigeria"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2023-03-22T08:00:00Z",
    createdAt: "2023-03-18T10:00:00Z",
    updatedAt: "2023-03-22T08:00:00Z",
    readTime: 7,
    views: 2800,
    likes: 190,
    seo: { metaTitle: "2 KOBO on Off-Plan Investment", metaDescription: "Lessons from off-plan real estate investing.", keywords: ["off-plan", "investment", "real estate"] },
  },
  {
    id: "blog-5",
    title: "Understanding the Property Market in Lekki: Insights for First-Time Buyers",
    slug: "understanding-property-market-lekki-first-time-buyers",
    excerpt: "First-time buyers navigating the Lekki property market need to understand pricing trends, neighborhood dynamics, and the right questions to ask.",
    content: "Lekki remains one of the most sought-after real estate markets in Nigeria, but it can be overwhelming for first-time buyers. Understanding the difference between Lekki Phase 1, Lekki Phase 2, Ibeju-Lekki, and the greater Lekki corridor is essential. Each sub-market has its own pricing dynamics, infrastructure maturity, and growth trajectory. This guide breaks down what first-time buyers need to know to make confident, informed decisions.",
    coverImage: blogImageAlt4,
    author: defaultAuthor,
    category: realEstate,
    tags: ["lekki", "first-time buyers", "property market", "lagos"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2023-02-14T08:00:00Z",
    createdAt: "2023-02-10T10:00:00Z",
    updatedAt: "2023-02-14T08:00:00Z",
    readTime: 8,
    views: 3600,
    likes: 250,
    seo: { metaTitle: "Property Market in Lekki for First-Time Buyers", metaDescription: "Insights for first-time buyers in the Lekki property market.", keywords: ["lekki", "first-time buyers", "property market"] },
  },
  {
    id: "blog-6",
    title: "7 Reasons to Invest in Off-Plan Properties in Lekki",
    slug: "7-reasons-invest-off-plan-properties-lekki",
    excerpt: "From lower entry prices to high capital appreciation, here are seven compelling reasons to consider off-plan properties in Lekki.",
    content: "Off-plan properties in Lekki offer lower purchase prices compared to completed units, flexible payment plans, and significant capital appreciation potential. The Lekki corridor's rapid infrastructure development — including the Lekki Deep Sea Port, the new airport, and the Lekki Free Trade Zone — is driving demand. Investors who enter early stand to benefit the most as these projects mature and property values rise.",
    coverImage: blogImageAlt5,
    author: defaultAuthor,
    category: realEstate,
    tags: ["off-plan", "lekki", "investment", "capital appreciation"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2023-01-25T08:00:00Z",
    createdAt: "2023-01-20T10:00:00Z",
    updatedAt: "2023-01-25T08:00:00Z",
    readTime: 6,
    views: 2900,
    likes: 200,
    seo: { metaTitle: "7 Reasons to Invest in Off-Plan Lekki", metaDescription: "Why off-plan properties in Lekki are a smart investment.", keywords: ["off-plan", "lekki", "investment"] },
  },
  {
    id: "blog-7",
    title: "Dos and Don'ts for a New Real Estate Agent in 2024",
    slug: "dos-and-donts-new-real-estate-agent-2024",
    excerpt: "Starting a career in real estate? Here are the essential dos and don'ts every new agent should know to build a sustainable practice.",
    content: "New real estate agents should focus on building genuine relationships, mastering their local market, and maintaining ethical standards. Do invest in continuous learning, build a strong online presence, and always prioritize your client's interests. Don't overpromise, neglect documentation, or cut corners on due diligence. The agents who succeed long-term are those who earn trust through transparency and consistent results.",
    coverImage: blogImageAlt6,
    author: defaultAuthor,
    category: business,
    tags: ["real estate agent", "career", "2024", "tips"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2022-12-10T08:00:00Z",
    createdAt: "2022-12-05T10:00:00Z",
    updatedAt: "2022-12-10T08:00:00Z",
    readTime: 7,
    views: 2400,
    likes: 170,
    seo: { metaTitle: "Dos and Don'ts for New Real Estate Agents", metaDescription: "Essential tips for new real estate agents in 2024.", keywords: ["real estate agent", "career", "tips"] },
  },
  {
    id: "blog-8",
    title: "7 Profitable Ventures to Consider with Your Bare Land in Nigeria",
    slug: "7-profitable-ventures-bare-land-nigeria",
    excerpt: "Owning bare land in Nigeria opens the door to multiple profitable ventures — from residential estates to commercial developments and agriculture.",
    content: "Bare land is one of the most versatile assets in Nigeria. Depending on location and size, you can develop residential estates, commercial complexes, industrial warehouses, or agricultural farms. The key is understanding zoning regulations, infrastructure access, and market demand in your area. This article explores seven proven ways to turn bare land into a profitable venture.",
    coverImage: blogImageAlt7,
    author: defaultAuthor,
    category: land,
    tags: ["bare land", "investment", "nigeria", "development"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2022-11-08T08:00:00Z",
    createdAt: "2022-11-02T10:00:00Z",
    updatedAt: "2022-11-08T08:00:00Z",
    readTime: 8,
    views: 3100,
    likes: 230,
    seo: { metaTitle: "Profitable Ventures with Bare Land in Nigeria", metaDescription: "Seven ways to profit from bare land in Nigeria.", keywords: ["bare land", "investment", "nigeria"] },
  },
  {
    id: "blog-9",
    title: "Buying Vs Renting a Home: What is the Major Difference",
    slug: "buying-vs-renting-home-major-difference",
    excerpt: "The buy vs rent decision is one of the biggest financial choices you'll make. Here's a clear breakdown of the key differences to help you decide.",
    content: "Buying a home builds equity and long-term wealth, while renting offers flexibility and lower upfront costs. The right choice depends on your financial situation, lifestyle, and long-term goals. In Nigeria's dynamic real estate market, understanding the total cost of ownership — including maintenance, taxes, and legal fees — versus the total cost of renting is essential for making an informed decision.",
    coverImage: blogImageAlt8,
    author: defaultAuthor,
    category: realEstate,
    tags: ["buying", "renting", "home", "real estate"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2022-10-12T08:00:00Z",
    createdAt: "2022-10-08T10:00:00Z",
    updatedAt: "2022-10-12T08:00:00Z",
    readTime: 6,
    views: 2700,
    likes: 180,
    seo: { metaTitle: "Buying Vs Renting a Home", metaDescription: "Key differences between buying and renting a home.", keywords: ["buying", "renting", "home"] },
  },
  {
    id: "blog-10",
    title: "6 Key Documents to Protect Your Property When Buying",
    slug: "6-key-documents-protect-property-buying",
    excerpt: "Protect your investment by ensuring these six critical documents are verified and in order before completing any property purchase.",
    content: "The six key documents every property buyer should verify are the Certificate of Occupancy (C of O) or Governor's Consent, the survey plan, the deed of assignment, the building approval plan, the tax clearance certificate, and the purchase receipt. Each document serves a specific legal purpose, and missing any one of them can expose you to fraud, disputes, or loss of investment. Always engage a qualified property lawyer to conduct due diligence.",
    coverImage: blogImageAlt9,
    author: defaultAuthor,
    category: realEstate,
    tags: ["documents", "property", "legal", "buying"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2022-09-20T08:00:00Z",
    createdAt: "2022-09-15T10:00:00Z",
    updatedAt: "2022-09-20T08:00:00Z",
    readTime: 7,
    views: 3400,
    likes: 260,
    seo: { metaTitle: "Key Documents to Protect Property", metaDescription: "Six documents every property buyer needs.", keywords: ["documents", "property", "legal"] },
  },
  {
    id: "blog-11",
    title: "10 Real Estate Market Trends in Nigeria",
    slug: "10-real-estate-market-trends-nigeria",
    excerpt: "From smart cities to co-living spaces, these ten trends are shaping the future of real estate in Nigeria.",
    content: "Nigeria's real estate market is being reshaped by urbanization, technology, and changing demographics. Key trends include the rise of smart cities, increased demand for affordable housing, growth of co-living and co-working spaces, and greater adoption of property technology (PropTech). Understanding these trends helps investors and homebuyers position themselves for the opportunities ahead.",
    coverImage: blogImageAlt10,
    author: defaultAuthor,
    category: realEstate,
    tags: ["market trends", "nigeria", "real estate", "2024"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2022-08-15T08:00:00Z",
    createdAt: "2022-08-10T10:00:00Z",
    updatedAt: "2022-08-15T08:00:00Z",
    readTime: 9,
    views: 4200,
    likes: 310,
    seo: { metaTitle: "Real Estate Market Trends in Nigeria", metaDescription: "Ten trends shaping Nigeria's real estate market.", keywords: ["market trends", "nigeria", "real estate"] },
  },
  {
    id: "blog-12",
    title: "Skills That You Can Learn In The Real Estate Market",
    slug: "skills-you-can-learn-real-estate-market",
    excerpt: "The real estate market is a classroom. Here are valuable skills you can develop by actively participating in property transactions.",
    content: "Participating in the real estate market teaches negotiation, financial analysis, market research, legal literacy, and relationship management. Whether you're buying your first home or building an investment portfolio, each transaction sharpens skills that are transferable to business and personal finance. This article explores the most valuable skills you can develop through real estate.",
    coverImage: blogImageAlt11,
    author: defaultAuthor,
    category: business,
    tags: ["skills", "real estate", "career", "learning"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2022-07-18T08:00:00Z",
    createdAt: "2022-07-12T10:00:00Z",
    updatedAt: "2022-07-18T08:00:00Z",
    readTime: 6,
    views: 2100,
    likes: 150,
    seo: { metaTitle: "Skills You Can Learn in Real Estate", metaDescription: "Valuable skills developed through real estate.", keywords: ["skills", "real estate", "learning"] },
  },
  {
    id: "blog-13",
    title: "Learn The Truth About Real Estate Industry",
    slug: "learn-truth-about-real-estate-industry",
    excerpt: "Separate fact from fiction. Here's an honest look at how the real estate industry actually works and what it takes to succeed.",
    content: "The real estate industry is often glamorized, but the truth is that success requires hard work, continuous learning, and ethical practice. From understanding market cycles to managing client expectations, the industry rewards those who invest in knowledge and integrity. This article breaks down the realities of working in real estate and what it takes to build a lasting career.",
    coverImage: blogImageAlt12,
    author: defaultAuthor,
    category: uncategorized,
    tags: ["real estate", "industry", "truth", "career"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2022-06-22T08:00:00Z",
    createdAt: "2022-06-18T10:00:00Z",
    updatedAt: "2022-06-22T08:00:00Z",
    readTime: 7,
    views: 1900,
    likes: 130,
    seo: { metaTitle: "Truth About Real Estate Industry", metaDescription: "An honest look at the real estate industry.", keywords: ["real estate", "industry", "truth"] },
  },
  {
    id: "blog-14",
    title: "10 Quick Tips About Business Development",
    slug: "10-quick-tips-business-development",
    excerpt: "Practical business development tips for real estate professionals looking to grow their practice and close more deals.",
    content: "Business development in real estate requires a strategic approach. Focus on building a strong personal brand, leveraging digital marketing, nurturing referral partnerships, and consistently following up with leads. The most successful agents treat business development as a daily discipline, not an occasional activity. These ten quick tips will help you accelerate your growth.",
    coverImage: blogImageAlt13,
    author: defaultAuthor,
    category: uncategorized,
    tags: ["business development", "tips", "real estate", "growth"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2022-05-30T08:00:00Z",
    createdAt: "2022-05-25T10:00:00Z",
    updatedAt: "2022-05-30T08:00:00Z",
    readTime: 5,
    views: 1800,
    likes: 120,
    seo: { metaTitle: "Quick Tips About Business Development", metaDescription: "Business development tips for real estate professionals.", keywords: ["business development", "tips", "real estate"] },
  },
  {
    id: "blog-15",
    title: "10 Quick Tips About Real Estate",
    slug: "10-quick-tips-about-real-estate",
    excerpt: "New to real estate? These ten quick tips will help you avoid common mistakes and make smarter property decisions from day one.",
    content: "Real estate can be complex, but a few foundational principles go a long way. Always verify documents, work with licensed professionals, understand your total costs, and never rush a purchase. Whether you're buying, selling, or investing, these ten quick tips will help you navigate the market with greater confidence and avoid costly mistakes.",
    coverImage: blogImageAlt14,
    author: defaultAuthor,
    category: uncategorized,
    tags: ["real estate", "tips", "beginners", "property"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2022-05-05T08:00:00Z",
    createdAt: "2022-04-30T10:00:00Z",
    updatedAt: "2022-05-05T08:00:00Z",
    readTime: 5,
    views: 2300,
    likes: 160,
    seo: { metaTitle: "Quick Tips About Real Estate", metaDescription: "Ten quick tips for real estate beginners.", keywords: ["real estate", "tips", "beginners"] },
  },
];