import type { Property, BlogPost, Testimonial, Agent } from "@/types";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-1",
    name: "Tunde Adeyemi",
    title: "Senior Real Estate Consultant",
    email: "tunde@futurehome.com",
    phone: "+234 801 234 5678",
    whatsapp: "+234 801 234 5678",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    bio: "With over 10 years of experience in Lagos real estate market, Tunde specializes in luxury residential properties.",
    licenseNumber: "Lagos/REC/2015/0042",
    yearsExperience: 10,
    specialties: ["Luxury Homes", "Commercial Properties", "Investment Properties"],
    languages: ["English", "Yoruba"],
    social: { linkedin: "https://linkedin.com/in/tunde", instagram: "https://instagram.com/tunde" },
    rating: 4.9,
    reviewCount: 127,
    propertiesCount: 89,
  },
  {
    id: "agent-2",
    name: "Chioma Eze",
    title: "Property Investment Advisor",
    email: "chioma@futurehome.com",
    phone: "+234 802 345 6789",
    whatsapp: "+234 802 345 6789",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=400&fit=crop&crop=face",
    bio: "Chioma helps investors identify high-yield properties across Lagos with data-driven insights.",
    licenseNumber: "Lagos/REC/2016/0078",
    yearsExperience: 8,
    specialties: ["Investment Properties", "Off-plan", "Rental Yield"],
    languages: ["English", "Igbo"],
    social: { linkedin: "https://linkedin.com/in/chioma", twitter: "https://twitter.com/chioma" },
    rating: 4.8,
    reviewCount: 95,
    propertiesCount: 67,
  },
  {
    id: "agent-3",
    name: "Abdul Balogun",
    title: "Commercial Real Estate Specialist",
    email: "abdul@futurehome.com",
    phone: "+234 803 456 7890",
    whatsapp: "+234 803 456 7890",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    bio: "Abdul has facilitated over ₦5 billion in commercial real estate transactions across Nigeria.",
    licenseNumber: "Lagos/REC/2014/0021",
    yearsExperience: 12,
    specialties: ["Commercial", "Industrial", "Land"],
    languages: ["English", "Hausa", "Arabic"],
    social: { linkedin: "https://linkedin.com/in/abdul" },
    rating: 4.7,
    reviewCount: 78,
    propertiesCount: 54,
  },
];

const createProperty = (overrides: Partial<Property>): Property => ({
  id: Math.random().toString(36).substr(2, 9),
  title: "Beautiful Property",
  description: "This is a stunning property located in one of the most prestigious neighborhoods in Lagos. Featuring modern amenities, spacious rooms, and breathtaking views.",
  shortDescription: "Stunning modern property in prime location",
  type: "apartment",
  status: "for-sale",
  category: "residential",
  listingType: "sale",
  price: 150000000,
  pricePerSqFt: 500000,
  currency: "NGN",
  location: {
    address: "1 Admiralty Way",
    city: "Lekki",
    state: "Lagos",
    country: "Nigeria",
    coordinates: { lat: 6.4474, lng: 3.4706 },
    neighborhood: "Lekki Phase 1",
    landmark: "Near Landmark Beach",
  },
  features: {
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 2,
    area: 300,
    areaUnit: "sqm",
    yearBuilt: 2022,
    floors: 1,
    floorNumber: 8,
  },
  amenities: {
    airConditioning: true,
    heating: false,
    furnished: false,
    kitchenAppliances: true,
    washerDryer: true,
    walkInCloset: true,
    fireplace: false,
    balcony: true,
    elevator: true,
    security: true,
    concierge: true,
    gym: true,
    pool: true,
    spa: false,
    tennisCourt: false,
    basketballCourt: false,
    playground: false,
    garden: true,
    rooftop: true,
    internet: true,
    cableTv: true,
    intercom: true,
    cctv: true,
    backupGenerator: true,
    solarPower: true,
    waterTreatment: true,
    wheelchairAccessible: true,
    petFriendly: true,
  },
  images: [
    { id: "1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", alt: "Property exterior", isPrimary: true, order: 0 },
    { id: "2", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop", alt: "Living room", isPrimary: false, order: 1 },
    { id: "3", url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop", alt: "Kitchen", isPrimary: false, order: 2 },
    { id: "4", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", alt: "Bedroom", isPrimary: false, order: 3 },
    { id: "5", url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&h=600&fit=crop", alt: "Bathroom", isPrimary: false, order: 4 },
  ],
  agent: MOCK_AGENTS[0],
  isFeatured: true,
  isVerified: true,
  views: 1250,
  favoritesCount: 89,
  createdAt: "2024-01-15T10:00:00Z",
  updatedAt: "2024-03-10T14:30:00Z",
  publishedAt: "2024-01-20T08:00:00Z",
  nearbyPlaces: [
    { id: "1", name: "Lekki Conservation Centre", type: "park", distance: 2500 },
    { id: "2", name: "Novare Mall", type: "shopping", distance: 1200 },
    { id: "3", name: "American International School", type: "school", distance: 1800 },
  ],
  ...overrides,
});

export const MOCK_PROPERTIES: Property[] = [
  createProperty({
    id: "prop-1",
    title: "Luxury Penthouse at Eko Atlantic",
    description: "An exquisite penthouse offering panoramic views of the Atlantic Ocean. This masterpiece features floor-to-ceiling windows, Italian marble finishes, and smart home automation throughout.",
    shortDescription: "Stunning ocean-view penthouse in Eko Atlantic",
    type: "penthouse",
    price: 850000000,
    location: { address: "Block 2, Plot 1", city: "Lagos", state: "Lagos", country: "Nigeria", neighborhood: "Eko Atlantic", coordinates: { lat: 6.4281, lng: 3.4286 } },
    features: { bedrooms: 5, bathrooms: 5, parkingSpaces: 3, area: 650, areaUnit: "sqm", yearBuilt: 2023, floorNumber: 30 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop", alt: "Penthouse exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop", alt: "Living room", isPrimary: false, order: 1 },
      { id: "3", url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop", alt: "Master bedroom", isPrimary: false, order: 2 },
      { id: "4", url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop", alt: "Kitchen", isPrimary: false, order: 3 },
    ],
    isFeatured: true,
    category: "luxury",
    agent: MOCK_AGENTS[1],
    views: 3200,
    favoritesCount: 245,
  }),
  createProperty({
    id: "prop-2",
    title: "Modern 4-Bedroom Duplex in Lekki",
    description: "A beautifully designed 4-bedroom fully detached duplex in a serene estate. Features include fitted kitchen, POP finishing, water heater, CCTV, and impressive architectural design.",
    shortDescription: "Spacious family home in prime Lekki location",
    type: "duplex",
    price: 120000000,
    location: { address: "ID Atlantic Estate, Lekki", city: "Lekki", state: "Lagos", country: "Nigeria", neighborhood: "Lekki Phase 1", coordinates: { lat: 6.4478, lng: 3.4720 } },
    features: { bedrooms: 4, bathrooms: 4, parkingSpaces: 2, area: 350, areaUnit: "sqm", yearBuilt: 2023, floors: 2 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop", alt: "Duplex exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&h=600&fit=crop", alt: "Living area", isPrimary: false, order: 1 },
      { id: "3", url: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop", alt: "Kitchen", isPrimary: false, order: 2 },
    ],
    isFeatured: true,
    agent: MOCK_AGENTS[0],
    views: 2100,
    favoritesCount: 156,
  }),
  createProperty({
    id: "prop-3",
    title: "Premium Apartment at Victoria Island",
    description: "An elegantly finished 3-bedroom apartment in a high-rise with city views. World-class amenities including gym, pool, and 24/7 security.",
    shortDescription: "Elegant apartment in upscale Victoria Island",
    type: "apartment",
    price: 200000000,
    location: { address: "15A Ozumba Mbadiwe Avenue", city: "Victoria Island", state: "Lagos", country: "Nigeria", neighborhood: "Victoria Island", coordinates: { lat: 6.4284, lng: 3.4266 } },
    features: { bedrooms: 3, bathrooms: 3, parkingSpaces: 2, area: 280, areaUnit: "sqm", yearBuilt: 2021, floorNumber: 12 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop", alt: "Apartment exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=600&fit=crop", alt: "Interior view", isPrimary: false, order: 1 },
      { id: "3", url: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&h=600&fit=crop", alt: "Balcony view", isPrimary: false, order: 2 },
    ],
    isFeatured: true,
    listingType: "rent",
    agent: MOCK_AGENTS[2],
    views: 1800,
    favoritesCount: 98,
  }),
  createProperty({
    id: "prop-4",
    title: "Beachfront Villa in Banana Island",
    description: "A prestigious beachfront villa offering unparalleled luxury. This architectural masterpiece sits on 2,000 sqm with private beach access and resort-style amenities.",
    shortDescription: "Exclusive beachfront living in Banana Island",
    type: "villa",
    price: 2500000000,
    location: { address: "Ocean Drive, Banana Island", city: "Ikoyi", state: "Lagos", country: "Nigeria", neighborhood: "Banana Island", coordinates: { lat: 6.4396, lng: 3.4290 } },
    features: { bedrooms: 7, bathrooms: 6, parkingSpaces: 5, area: 1200, areaUnit: "sqm", yearBuilt: 2020, floors: 2 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", alt: "Villa exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", alt: "Pool area", isPrimary: false, order: 1 },
      { id: "3", url: "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&h=600&fit=crop", alt: "Interior", isPrimary: false, order: 2 },
    ],
    isFeatured: true,
    category: "luxury",
    agent: MOCK_AGENTS[1],
    views: 4500,
    favoritesCount: 312,
  }),
  createProperty({
    id: "prop-5",
    title: "Contemporary Office Space in GRA Ikeja",
    description: "Grade A office space of 500 sqm in a central business district with excellent accessibility, ample parking, and fiber optic connectivity.",
    shortDescription: "Prime commercial space in GRA Ikeja business district",
    type: "office",
    price: 350000000,
    listingType: "sale",
    category: "commercial",
    location: { address: "Oba Akran Avenue", city: "Ikeja", state: "Lagos", country: "Nigeria", neighborhood: "GRA Ikeja", coordinates: { lat: 6.5964, lng: 3.3420 } },
    features: { bedrooms: 0, bathrooms: 4, parkingSpaces: 10, area: 500, areaUnit: "sqm", yearBuilt: 2022, floorNumber: 15 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop", alt: "Office building", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop", alt: "Office interior", isPrimary: false, order: 1 },
    ],
    isFeatured: false,
    agent: MOCK_AGENTS[2],
    views: 890,
    favoritesCount: 45,
  }),
  createProperty({
    id: "prop-6",
    title: "Serviced Apartment in Oniru",
    description: "Fully serviced 2-bedroom apartment with hotel-like amenities. High-speed internet, daily cleaning, concierge, and 24-hour power supply included.",
    shortDescription: "Hotel-style serviced apartment in Oniru",
    type: "apartment",
    price: 65000000,
    listingType: "rent",
    location: { address: "King George V Drive, Oniru", city: "Victoria Island", state: "Lagos", country: "Nigeria", neighborhood: "Oniru", coordinates: { lat: 6.4350, lng: 3.4310 } },
    features: { bedrooms: 2, bathrooms: 2, parkingSpaces: 1, area: 120, areaUnit: "sqm", yearBuilt: 2023, floorNumber: 5 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", alt: "Apartment exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop", alt: "Living area", isPrimary: false, order: 1 },
    ],
    isFeatured: false,
    agent: MOCK_AGENTS[0],
    views: 1340,
    favoritesCount: 78,
  }),
  createProperty({
    id: "prop-7",
    title: "Massive Land in Ibeju-Lekki",
    description: "An exceptional investment opportunity - 2,000 square meters of dry, well-located land in the rapidly developing Ibeju-Lekki corridor. Perfect for residential or commercial development.",
    shortDescription: "Premium dry land in Ibeju-Lekki corridor",
    type: "land",
    price: 45000000,
    listingType: "sale",
    category: "land",
    location: { address: "Lakowe Lakes Road, Ibeju-Lekki", city: "Ibeju-Lekki", state: "Lagos", country: "Nigeria", coordinates: { lat: 6.4956, lng: 3.5988 } },
    features: { bedrooms: 0, bathrooms: 0, parkingSpaces: 0, area: 2000, areaUnit: "sqm", yearBuilt: 0 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop", alt: "Land view", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&h=600&fit=crop", alt: "Surrounding area", isPrimary: false, order: 1 },
    ],
    isFeatured: false,
    agent: MOCK_AGENTS[2],
    views: 670,
    favoritesCount: 34,
  }),
  createProperty({
    id: "prop-8",
    title: "Waterfront Home in Chevron",
    description: "Stunning 5-bedroom terrace home along the Chevron waterfront. Features private dock, home automation, staff quarters, and manicured gardens.",
    shortDescription: "Waterfront luxury home with private dock",
    type: "townhouse",
    price: 380000000,
    location: { address: "Chevron Drive", city: "Lekki", state: "Lagos", country: "Nigeria", neighborhood: "Chevron", coordinates: { lat: 6.4410, lng: 3.4660 } },
    features: { bedrooms: 5, bathrooms: 5, parkingSpaces: 3, area: 450, areaUnit: "sqm", yearBuilt: 2022, floors: 3 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", alt: "Home exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop", alt: "Living room", isPrimary: false, order: 1 },
      { id: "3", url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop", alt: "Waterfront view", isPrimary: false, order: 2 },
    ],
    isFeatured: true,
    agent: MOCK_AGENTS[1],
    views: 2800,
    favoritesCount: 198,
  }),
  createProperty({
    id: "prop-9",
    title: "Student Accommodation in Yaba",
    description: "Well-designed 1-bedroom apartment in bustling Yaba area, perfect for young professionals or students. Close to tech hubs and educational institutions.",
    shortDescription: "Affordable modern apartment in Yaba",
    type: "apartment",
    price: 25000000,
    listingType: "rent",
    location: { address: "Akibo Close, Yaba", city: "Yaba", state: "Lagos", country: "Nigeria", neighborhood: "Yaba", coordinates: { lat: 6.5095, lng: 3.3792 } },
    features: { bedrooms: 1, bathrooms: 1, parkingSpaces: 1, area: 55, areaUnit: "sqm", yearBuilt: 2021, floorNumber: 3 },
    images: [
      { id: "1", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop", alt: "Apartment exterior", isPrimary: true, order: 0 },
      { id: "2", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop", alt: "Interior", isPrimary: false, order: 1 },
    ],
    isFeatured: false,
    agent: MOCK_AGENTS[0],
    views: 920,
    favoritesCount: 56,
  }),
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "Dr. Funke Akindele",
    role: "Medical Doctor",
    company: "Lagos University Teaching Hospital",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    content: "Future Home Properties made our dream of owning a home in Victoria Island a reality. Their professionalism, market knowledge, and dedication to finding the perfect property for our family was outstanding. We couldn't be happier with our new home!",
    rating: 5,
    propertyId: "prop-3",
    propertyTitle: "Premium Apartment at Victoria Island",
    createdAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "test-2",
    name: "Emeka Obi",
    role: "Tech Entrepreneur",
    company: "FinTech Solutions",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
    content: "As a busy professional, I needed a property agent who understood my requirements and could handle everything efficiently. Future Home exceeded all expectations. They found me a perfect investment property that has already appreciated significantly.",
    rating: 5,
    propertyId: "prop-5",
    propertyTitle: "Contemporary Office Space in GRA Ikeja",
    createdAt: "2024-01-28T10:00:00Z",
  },
  {
    id: "test-3",
    name: "Aisha Musa",
    role: "Banking Executive",
    company: "First Bank of Nigeria",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
    content: "I've worked with several real estate companies, but none compare to Future Home Properties. Their attention to detail, transparent communication, and genuine care for their clients sets them apart. They truly go above and beyond.",
    rating: 5,
    propertyId: "prop-8",
    propertyTitle: "Waterfront Home in Chevron",
    createdAt: "2024-03-05T10:00:00Z",
  },
  {
    id: "test-4",
    name: "Oluwaseun Adeyinka",
    role: "Real Estate Investor",
    company: "Adeyinka Holdings",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    content: "Future Home Properties has been instrumental in building my real estate portfolio. Their investment advice is always sound, and they have an uncanny ability to identify properties with the highest ROI potential. Truly top-notch service.",
    rating: 5,
    propertyId: "prop-7",
    propertyTitle: "Massive Land in Ibeju-Lekki",
    createdAt: "2024-02-20T10:00:00Z",
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    title: "Top 10 Real Estate Investment Opportunities in Lagos for 2024",
    slug: "top-real-estate-investment-opportunities-lagos-2024",
    excerpt: "Discover the most promising real estate investment opportunities in Lagos this year. From emerging neighborhoods to established prime locations, we cover it all.",
    content: "Lagos real estate market continues to show remarkable resilience and growth potential in 2024. With ongoing infrastructure development and expanding economic opportunities, several key areas stand out for investors...",
    coverImage: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop",
    author: { id: "author-1", name: "Tunde Adeyemi", title: "Senior Consultant", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face", bio: "Real estate expert with 10+ years", social: { linkedin: "#" } },
    category: { id: "cat-1", name: "Investment", slug: "investment", description: "Real estate investment insights", postCount: 15 },
    tags: ["investment", "lagos", "2024", "real estate"],
    isFeatured: true,
    isPublished: true,
    publishedAt: "2024-03-01T08:00:00Z",
    createdAt: "2024-02-28T10:00:00Z",
    updatedAt: "2024-03-01T08:00:00Z",
    readTime: 8,
    views: 2450,
    likes: 187,
    seo: { metaTitle: "Top Real Estate Investments Lagos 2024", metaDescription: "Best investment opportunities in Lagos real estate", keywords: ["lagos real estate", "investment", "2024"] },
  },
  {
    id: "blog-2",
    title: "A Complete Guide to Buying Property in Nigeria",
    slug: "complete-guide-buying-property-nigeria",
    excerpt: "Everything you need to know about buying property in Nigeria - from legal requirements to financing options and common pitfalls to avoid.",
    content: "Buying property in Nigeria requires careful planning and understanding of the legal framework. This comprehensive guide covers all aspects of the process...",
    coverImage: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200&h=800&fit=crop",
    author: { id: "author-2", name: "Bar. Femi Sanni", title: "Legal Adviser", image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face", bio: "Property law specialist", social: { linkedin: "#" } },
    category: { id: "cat-2", name: "Guide", slug: "guide", description: "Property buying guides", postCount: 12 },
    tags: ["guide", "buying", "property", "nigeria"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2024-02-25T08:00:00Z",
    createdAt: "2024-02-20T10:00:00Z",
    updatedAt: "2024-02-25T08:00:00Z",
    readTime: 12,
    views: 3200,
    likes: 245,
    seo: { metaTitle: "Guide to Buying Property Nigeria", metaDescription: "Complete guide for property buyers", keywords: ["buy property", "nigeria", "guide"] },
  },
  {
    id: "blog-3",
    title: "Luxury Real Estate: What Defines Premium Properties",
    slug: "luxury-real-estate-premium-properties",
    excerpt: "From architectural design to smart home features, learn what makes a property truly luxury in today's Nigerian real estate market.",
    content: "The definition of luxury property in Nigeria is evolving. No longer defined solely by size and opulence, today's premium properties combine cutting-edge technology, sustainable design, and exceptional locations...",
    coverImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop",
    author: { id: "author-3", name: "Chioma Eze", title: "Investment Advisor", image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=400&fit=crop&crop=face", bio: "Luxury property specialist", social: { linkedin: "#" } },
    category: { id: "cat-3", name: "Luxury", slug: "luxury", description: "Luxury property insights", postCount: 8 },
    tags: ["luxury", "premium", "real estate", "design"],
    isFeatured: true,
    isPublished: true,
    publishedAt: "2024-02-18T08:00:00Z",
    createdAt: "2024-02-15T10:00:00Z",
    updatedAt: "2024-02-18T08:00:00Z",
    readTime: 10,
    views: 1890,
    likes: 156,
    seo: { metaTitle: "Luxury Real Estate Premium Properties", metaDescription: "What defines luxury property in Nigeria", keywords: ["luxury", "premium", "real estate"] },
  },
  {
    id: "blog-4",
    title: "Understanding Property Valuation: How Much is Your Property Worth?",
    slug: "understanding-property-valuation",
    excerpt: "Learn the factors that determine property value in Nigeria and how to get an accurate assessment for buying or selling.",
    content: "Property valuation is a crucial aspect of real estate transactions. Several factors influence the value of a property, including location, size, condition, and market dynamics...",
    coverImage: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=1200&h=800&fit=crop",
    author: { id: "author-1", name: "Tunde Adeyemi", title: "Senior Consultant", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face", bio: "Real estate expert with 10+ years", social: { linkedin: "#" } },
    category: { id: "cat-2", name: "Guide", slug: "guide", description: "Property buying guides", postCount: 12 },
    tags: ["valuation", "property value", "appraisal", "real estate"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2024-02-10T08:00:00Z",
    createdAt: "2024-02-08T10:00:00Z",
    updatedAt: "2024-02-10T08:00:00Z",
    readTime: 7,
    views: 1560,
    likes: 98,
    seo: { metaTitle: "Property Valuation Guide Nigeria", metaDescription: "How to value property in Nigeria", keywords: ["valuation", "property", "value"] },
  },
  {
    id: "blog-5",
    title: "Commercial Real Estate: Opportunities in Nigeria's Growing Business Districts",
    slug: "commercial-real-estate-opportunities-nigeria",
    excerpt: "Explore the booming commercial real estate sector in Nigeria's major business districts from Lagos to Abuja.",
    content: "Nigeria's commercial real estate market is experiencing significant growth, driven by expanding business activities and favorable economic policies...",
    coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop",
    author: { id: "author-4", name: "Abdul Balogun", title: "Commercial Specialist", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face", bio: "Commercial real estate expert", social: { linkedin: "#" } },
    category: { id: "cat-1", name: "Investment", slug: "investment", description: "Real estate investment insights", postCount: 15 },
    tags: ["commercial", "business", "offices", "real estate"],
    isFeatured: false,
    isPublished: true,
    publishedAt: "2024-02-05T08:00:00Z",
    createdAt: "2024-02-03T10:00:00Z",
    updatedAt: "2024-02-05T08:00:00Z",
    readTime: 9,
    views: 1340,
    likes: 87,
    seo: { metaTitle: "Commercial Real Estate Nigeria", metaDescription: "Commercial property opportunities", keywords: ["commercial", "real estate", "business"] },
  },
];